### PR TITLE
Add code coverage support in pipeline - Fixes #61

### LINKED ISSUE #60: Update Sampler Build Tasks
Update the Sampler Build tasks as per this blog post: https://dsccommunity.org/blog/updating-sampler-github-tasks/

### LINKED ISSUE #61: Enable Code Coverage Reporting
Enable code coverage reporting as per this blog post: https://dsccommunity.org/blog/add-codecov-support-to-repository/

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR adds support for code coverage reporting in the pipeline and updates to use Sampler GitHub tasks.

#### This Pull Request (PR) fixes the following issues

- Fixes #60 
- Fixes #61 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing when you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62#-:-MYuZWiJ-9FwAaSJKH3t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 86 at r1](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62#-MYu_HWl67LYKWSpRVFQ:-MYu_HWm3mAJLBjmDLI8:blhotjq) ([raw file](https://github.com/dsccommunity/filecontentdsc/blob/1227af4dd504a0da7f8a3c4ab85aa9234a87e13e/azure-pipelines.yml#L86)):*
> ```
> - job: Test_Unit_2016
> ```

This job is not uploading the test artifact, so the pipeline fails.

**Review by PlagueHO — COMMENTED** [review]
Could review again @johlju ? Thankk you!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62#-:-MYx1c5oEBOY8biodnXr:bz8qq5s)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[azure-pipelines.yml, line 86 at r1](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62#-MYu_HWl67LYKWSpRVFQ:-MYx1_JaD_rC2VSocG-Z:b-896fix) ([raw file](https://github.com/dsccommunity/filecontentdsc/blob/1227af4dd504a0da7f8a3c4ab85aa9234a87e13e/azure-pipelines.yml#L86)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> - job: Test_Unit_2016
> ```

This job is not uploading the test artifact, so the pipeline fails. 
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filecontentdsc/62#-:-MZ1qmSH2iYJcnR0r4vr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
